### PR TITLE
chore(ci): upload apk to github release

### PR DESCRIPTION
**Pull request by qtdzz**
## Description
- Add steps to build APK, upload to action artifact, and create a draft GH release note with the APK if the workflow is triggered by tags push event.
- If you trigger the workflow manually, the APK is still built and uploaded to the workflow artifact but it doesn't create a GH release.
- My tests: 
  - https://github.com/qtdzz/medito-app/releases/tag/v2.0.23-test-do-not-use
  - https://github.com/qtdzz/medito-app/actions/runs/1043089957
  - How the badge in README looks like: https://github.com/qtdzz/medito-app/tree/github-apk#download-the-app (Note: it's showing the latest release as `v2.0.21` because it is looking for the latest GH release, not the latest tag)
## Next steps
- You will need to fill in the release certificate fingerprints as I mention in the VERIFY_APK.md, so that people can be sure that they are using legit APK. (I am not sure if it is the correct way to do so, please suggest if you have a better one)

### CODE REVIEW

**Comment by michaelcspeed** [comment]
This looks great @qtdzz ! I will take a look at the fingerprints ASAP :)

**Comment by scouech** [comment]
@michaelcspeed is this all good? :)

**Comment by michaelcspeed** [comment]
I was having some trouble with the configuration when I last had a go. I'll look at it again soon.

**Comment by ghost** [comment]
Any update on this?

**Review by michaelcspeed — APPROVED** [review]

**Comment by michaelcspeed** [comment]
Thank you @qtdzz, sorry for being super slow on this..

**Pull request merged**
