### PR TITLE
chore(ci): add fastlane beta github action workflow for Android

### PR DESCRIPTION
**Pull request by qtdzz**
## Description 

First attempt to automate the Android release process using [Fastlane](https://docs.fastlane.tools/) and GH Actions. I mainly followed the instruction in https://flutter.dev/docs/deployment/cd and took example from [Flutter Gallery](https://github.com/flutter/gallery/blob/master/) project.

## Prerequisites

This PR requires the following GH secrets to be able to work:
- For creating `auth.dart`:
  - `AUTH_BASE_URL` : real value for production
  - `AUTH_SENTRY_URL` : real value for production
  - `AUTH_CONTENT_TOKEN` : real value for production
  - `AUTH_INIT_TOKEN` : real value for production
- For signing Android app:
  - `FCI_KEY_ALIAS`: key alias
  - `FCI_KEY_PASSWORD`: key password
  - `FCI_KEYSTORE_PASSWORD`: keystore password
  - `PLAY_STORE_UPLOAD_KEY`: base64 encoded string of the `keystore.jks` file (It can be generated by `base64 path/to/keystore.jks > output.txt`). This string will be decoded in a GH action and written into `android/app/upload-keystore.jks`. `upload-keystore.jks` will be set as `FCI_KEYSTORE_PATH`.
  - `PLAY_STORE_CONFIG_JSON`:  you can get this from developer console https://docs.fastlane.tools/getting-started/android/setup/#collect-your-google-credentials. This file is used in fastlane to upload the artifacts into play store

## How to trigger the workflow

- The `beta` workflow will be triggered automatically on pushing tags event. The tags must be prefix with `v`, such as `v2.0.17`, `v3.0.0`. It will build the android app and upload to playstore
- The `promote_to_production` needs to be triggered manually by inputting the lane name `promote_to_production`. It won't build the project but just take the latest version from beta track and promote to production track.
- Similarly, `production` lane also need to be triggered manually by inputting the lane name `production`. It will build the appbundle and put to production track in playstore.
- All three lanes are configured to create a draft release. You will eventually have to press the final button to release them. We can change it to a fully automated workflow when the process is mature enough.
- Note: obviously, these triggers can be can to any desired behaviors. Please let me know if you want so. 

Related https://github.com/meditohq/medito-app/issues/55

### CODE REVIEW

**Comment by michaelcspeed** [comment]
Hey, this is great, thanks again. @qtdzz I've added all the GH secrets 🎉  The keystore will be valid from tomorrow

**Comment by qtdzz** [comment]
Cool. I'm very happy to hear. Hopefully it will work as we expect.
Please let me know if there is any problem when you are testing it. If everything goes well, we can start working on the counter part for iOS as well (which will require even more work from you side... 😟)

**Review by michaelcspeed — COMMENTED** [review]
looks good to me!

**Comment by michaelcspeed** [comment]
Hey @tsuki-no-usagi  I tried running the [workflow](https://github.com/meditohq/medito-app/actions/runs/881460553/workflow) but there is an error.

> The workflow is not valid. .github/workflows/deploy_to_playstore.yml (Line: 33, Col: 11): A sequence was not expected

I'm not sure what it means. It looks valid to me! Any ideas?

**Pull request merged**
