### PR TITLE
needed changes to get the app on android TV

### PR DESCRIPTION
**Pull request by h0ru5**
will need to add necessary keys to app manifest and ensure the tiles are clickable with the remote

### CODE REVIEW

**Comment by h0ru5** [comment]
I did test it as far as i can here, I  would need dev keys for the API to go further - is there any possibility for you guys to test & merge this?

**Comment by michaelcspeed** [comment]
Hey @h0ru5 is this ready to merge? :)

**Comment by michaelcspeed** [comment]
@h0ru5 gentle nudge :)

**Comment by h0ru5** [comment]
Hmm... not yet. it's usable on TV with the modifications I did, but the home screen is still causing issues.
As a workaround, I now start with the packs screen, and this works ok. 
maybe I can restrict it to do this only on TVs.  

it's not clear to me how flutter assigns the focus order at all.

**Comment by michaelcspeed** [comment]
https://docs.flutter.dev/development/ui/advanced/focus#controlling-what-gets-focus

Not sure if this helps? Apparently it's a new page.

We are planning to remove the Packs screen soon (and move it/replace it) because apparently a lot of user's don't see it. 🤷

**Comment by scouech** [comment]
Closing this. Medito will not be on TV for now. Thanks everyone!

**Pull request closed without merging**
